apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-is
  namespace: "cicd"
data:
  application.properties: |
    healthindicators.Adapters.enabled=true
    healthindicators.Cluster.enabled=true
    healthindicators.Cluster.properties.threshold.value=2
    healthindicators.Diskspace.enabled=true
    healthindicators.Diskspace.properties.threshold.value=10
    healthindicators.JDBC.enabled=true
    healthindicators.JMS.enabled=true
    healthindicators.JNDIAliases.enabled=false
    healthindicators.Memory.enabled=true
    healthindicators.Memory.properties.threshold.value=10
    healthindicators.RemoteServers.enabled=true
    healthindicators.SFTPServers.enabled=true
    healthindicators.ServiceThread.enabled=true
    healthindicators.ServiceThread.properties.threshold.value=10
    healthindicators.Sessions.enabled=true
    healthindicators.Sessions.properties.threshold.value=85
    healthindicators.UMAliases.enabled=true
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp\://universalmessaging.swag-infra\:9000
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "wm-builder"
  namespace: "cicd"
  labels:
    app: "wm-builder"
spec:
  selector:
    matchLabels:
      app: "wm-builder" 
  template: 
    metadata:
      labels:
        app: "wm-builder"
    spec:
      containers:
        - name: "wm-builder"
          image: "registry.k8s/wmbuilder:latest"
          workingDir: "/tmp"
          env:
            - name: "JENKINS_URL"
              value: "http://jenkins.cicd/"
            - name: "JENKINS_TUNNEL"
              value: "jenkins-agent.cicd:50000"
            - name: "JENKINS_AGENT_WORKDIR"
              value: "/tmp"
            - name: "JENKINS_AGENT_NAME"
              value: "wMBuilder"
            - name: "JENKINS_SECRET"
              value: "@/etc/jenkins/jenkins-secret.txt"
            - name: "SAG_IS_CONFIG_PROPERTIES"
              value: "/opt/swagmsr/config/application.properties"
          ports:
            - containerPort: 5555
              protocol: "TCP"
          volumeMounts:
            - name: config-volume
              mountPath: "/opt/swagmsr/config"
            - name: license-file
              mountPath: "/opt/softwareag/IntegrationServer/config/licenseKey.xml"
              subPath: "0000497888_MicroservicesRuntime_100.xml"
            - name: jenkins-secret
              mountPath: "/etc/jenkins"
      volumes:
        - name: config-volume
          configMap:
            name: application-properties-is
        - name: license-file
          configMap:
            name: msr-license
        - name: jenkins-secret
          secret: 
            secretName: "jenkins-secret"
            optional: false
  replicas: 1
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "wm-test"
  namespace: "swag-infra"
  labels:
    app: "wm-test"
spec:
  selector:
    matchLabels:
      app: "wm-test" 
  template: 
    metadata:
      labels:
        app: "wm-test"
    spec:
      containers:
        - name: "wm-test"
          image: "sagcr.azurecr.io/webmethods-microservicesruntime:10.15.0.1-ubi"
          ports:
            - containerPort: 5555
              protocol: "TCP"
          volumeMounts:
            - name: license-file
              mountPath: "/opt/softwareag/IntegrationServer/config/licenseKey.xml"
              subPath: "0000497888_MicroservicesRuntime_100.xml"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: license-file
          configMap:
            name: msr-license
  replicas: 1
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "wm-production"
  namespace: "swag-infra"
  labels:
    app: "wm-production"
spec:
  selector:
    matchLabels:
      app: "wm-production" 
  template: 
    metadata:
      labels:
        app: "wm-production"
    spec:
      containers:
        - name: "wm-production"
          image: "sagcr.azurecr.io/webmethods-microservicesruntime:10.15.0.1-ubi"
          ports:
            - containerPort: 5555
              protocol: "TCP"
          volumeMounts:
            - name: license-file
              mountPath: "/opt/softwareag/IntegrationServer/config/licenseKey.xml"
              subPath: "0000497888_MicroservicesRuntime_100.xml"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: license-file
          configMap:
            name: msr-license
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wm-builder
  name: wm-builder-service
  namespace: cicd
spec: 
  ports:
    - name: wmadmin
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: wm-builder
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wm-test
  name: wm-test-service
  namespace: swag-infra
spec: 
  ports:
    - name: wmadmin
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: wm-test
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wm-production
  name: wm-production-service
  namespace: swag-infra
spec: 
  ports:
    - name: wmadmin
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: wm-production
  type: LoadBalancer